DATASET_PATH = 'dataset'
OUTPUT_PATH = 'dist'
PICKLE_PATH = 'pickle'

SEED = 0
VALIDATION_SPLIT = 0.2
IMAGE_SIZE = (512, 384)

MODEL_NUM_EPOCHS = 5
MODEL_BATCH_SIZE = 1024
MODEL_WORKERS = 32

LOADER_BATCH_SIZE = 32
